name: Console Log Checker
on:
  pull_request:
    types: [opened, reopened, synchronize, closed, ready_for_review]

jobs:
  consoleLogChecker:
    uses: pkelly-rh/test-github-actions/.github/workflows/action.yaml@c7eac4de1546892c99f90184df9e8d4945acb5ef
