name: Console Log Checker
on:
  pull_request:
    types: [opened, reopened, synchronize, closed, ready_for_review]

jobs:
  consoleLogChecker:
    uses: pkelly-rh/test-github-actions/.github/workflows/console-log-guard.yml@239fa3291dcba50bcd420b50db573f745f08459a
    # {owner}/{repo}/{path}/{filename}@{ref}
